const mongoose=require("mongoose")


const productSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true,
    },
    description:{
        type:String,
        required:true,
    },
    discountPrice:{
        type:Number,
    },
    price:{
        type:Number,
        required:true,
    },
    sku:{
        type:String,
        required:true,
        unique:true,
    },
    category:{
        type:String,
        required:true,
    },
    stock:{
        type:Number,
        required:true,
        default:0,
    },
    brand:{
        type:String,
        required:true,
    },
    sizes:{
        type:[String],
        required:true,
    },
    colors:{
        type:[String],
        required:true,
    },
    collections:{
        type:String,
        required:true,
    },
    materials:{
        type:String,
        required:true,
    },
    gender:{
        type:String,
        enum:["men","women","unisex"],
    },
    images:[
        {
            url:{
                type:String,
                required:true,
            },
            altText:{
                type:String,
            }
        }
    ],
    isFeatured:{
        type:Boolean,
        default:false,
    },
    isPublished:{
        type:Boolean,
        default:false,
    },
    rating:{
        type:Number,
        default:0,
    },
    numReviews:{
        type:Number,
        default:0,
    },
    tags:[String],
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true,
    },
    metaTitle:{
        type:String,
    },
    metaDescription:{
        type:String,
    },
    metaKeywords:{
        type:String,
    },
    dimensions:{
        length:Number,
        width:Number,
        height:Number,   
    },
    weight:Number,
    
},{timestamps:true}
);

module.exports=mongoose.model("Product",productSchema);